package cache

import (
	"github.com/stretchr/testify/mock"
)

// MockMetrics is an autogenerated mock type for the Metrics type
type MockMetrics struct {
	mock.Mock
}

// Track provides a mock function with given fields: event
func (_m *MockMetrics) Track(event Event) {
	_m.Called(event)
}
